#!/bin/bash
cp ./holbertonschool-low_level_programming/0x04-more_functions_nested_loops/0-isupper.c /home/developer/holbertonschool-low_level_programming/0x09-static_libraries
cp ./holbertonschool-low_level_programming/0x07-pointers_arrays_strings/0-memset.c /home/developer/holbertonschool-low_level_programming/0x09-static_libraries
cp ./holbertonschool-low_level_programming/0x06-pointers_arrays_strings/0-strcat.c /home/developer/holbertonschool-low_level_programming/0x09-static_libraries
cp ./holbertonschool-low_level_programming/0x04-more_functions_nested_loops/1-isdigit.c /home/developer/holbertonschool-low_level_programming/0x09-static_libraries
cp ./holbertonschool-low_level_programming/0x07-pointers_arrays_strings/1-memcpy.c /home/developer/holbertonschool-low_level_programming/0x09-static_libraries
cp ./holbertonschool-low_level_programming/0x06-pointers_arrays_strings/1-strncat.c /home/developer/holbertonschool-low_level_programming/0x09-static_libraries
cp ./holbertonschool-low_level_programming/0x07-pointers_arrays_strings/2-strchr.c /home/developer/holbertonschool-low_level_programming/0x09-static_libraries
cp ./holbertonschool-low_level_programming/0x05-pointers_arrays_strings/2-strlen.c /home/developer/holbertonschool-low_level_programming/0x09-static_libraries
cp ./holbertonschool-low_level_programming/0x06-pointers_arrays_strings/2-strncpy.c /home/developer/holbertonschool-low_level_programming/0x09-static_libraries
cp ./holbertonschool-low_level_programming/0x02-functions_nested_loops/3-islower.c /home/developer/holbertonschool-low_level_programming/0x09-static_libraries
cp ./holbertonschool-low_level_programming/0x05-pointers_arrays_strings/3-puts.c /home/developer/holbertonschool-low_level_programming/0x09-static_libraries
cp ./holbertonschool-low_level_programming/0x06-pointers_arrays_strings/3-strcmp.c /home/developer/holbertonschool-low_level_programming/0x09-static_libraries
cp ./holbertonschool-low_level_programming/0x02-functions_nested_loops/4-isalpha.c /home/developer/holbertonschool-low_level_programming/0x09-static_libraries
cp ./holbertonschool-low_level_programming/0x02-functions_nested_loops/6-abs.c /home/developer/holbertonschool-low_level_programming/0x09-static_libraries
cp ./holbertonschool-low_level_programming/0x05-pointers_arrays_strings/9-strcpy.c /home/developer/holbertonschool-low_level_programming/0x09-static_libraries
cp ./holbertonschool-low_level_programming/0x02-functions_nested_loops/_putchar.c /home/developer/holbertonschool-low_level_programming/0x09-static_libraries
cp ./holbertonschool-low_level_programming/0x04-more_functions_nested_loops/_putchar.c /home/developer/holbertonschool-low_level_programming/0x09-static_libraries
cp ./holbertonschool-low_level_programming/0x05-pointers_arrays_strings/_putchar.c /home/developer/holbertonschool-low_level_programming/0x09-static_libraries
cp ./holbertonschool-low_level_programming/0x06-pointers_arrays_strings/_putchar.c /home/developer/holbertonschool-low_level_programming/0x09-static_libraries
cp ./holbertonschool-low_level_programming/0x08-recursion/_putchar.c /home/developer/holbertonschool-low_level_programming/0x09-static_libraries